### ISSUE TITLE
Calculate CCN for skip (IterImplSkip.java) by hand

### ISSUE THREAD

**Issue by AdderAdder** [bohrnsen/json-iterator-java#1]

**Comment by Fluffigpegasus** [comment]
Closed. See latex file.

**Comment by Fluffigpegasus** [comment]
![skip iterimplskip _madde](https://user-images.githubusercontent.com/14206196/36643383-aaee5680-1a4a-11e8-86f3-92f3760f2845.png)

**Comment by AdderAdder** [comment]
![skip interimplskip _johannes 1](https://user-images.githubusercontent.com/12662417/36645982-819bae32-1a71-11e8-9f2b-dd12dc6ceb7e.png)
