### ISSUE TITLE
Describe how you would refactor readStringSlowPath (IterImplForStreaming.java)

### ISSUE THREAD

**Issue by Fluffigpegasus** [bohrnsen/json-iterator-java#12]
For Sara or Oscar

**Comment by saraervik** [comment]
This code is never called, but I have wrote about it in the documentation. Would consider the issue done.

Review? @bohrnsen @OscarMelin @Fluffigpegasus @AdderAdder

**Comment by Fluffigpegasus** [comment]
The suggestion of removing it makes sense!
