### ISSUE TITLE
Refactor createDecoder (GsonCompatibilityMode.java)

### ISSUE THREAD

**Issue by saraervik** [bohrnsen/json-iterator-java#19]
Carry out the refactoring described in #14

**Comment by saraervik** [comment]
I did an attempt on this one, the refactoring itself is not difficult, but the class is currently not tested and I did not succeed on writing test for it. 

Hmm ... and I am not really sure about the use of this function. I have written a plan for refactoring, so if anyone else want to try refactoring this have a look at #14

**Comment by saraervik** [comment]
I set the label to won't fix, there are probably better functions to focus on! But like I wrote in the last comment, if you want to, go ahead 😄

**Comment by Fluffigpegasus** [comment]
Hi! You don't need to perform the actual refactoring, only write the plan for it. I have read your plan in the latex file. It looks good! Will close this issue now.
