### ISSUE TITLE
Calculate CCN for chooseImpl (Codegen.java) by hand

### ISSUE THREAD

**Issue by bohrnsen** [bohrnsen/json-iterator-java#2]
The cyclomatic complexity should be calculated using the formula proposed by Thomas J. McCabe.
Lizard should be used to compare the result, but the result does not need to be exactly the same since there exist some flaws in the declaration of McCabes method. 
Some control structures can be interpreted differently when creating a control flow graph.

**Comment by bohrnsen** [comment]
This is my first attempt at calculating the CCN by hand.

<img width="364" alt="chooseimpl" src="https://user-images.githubusercontent.com/5678082/36637595-a31d535e-19df-11e8-9697-98b0c0d69b32.png">

**Comment by AdderAdder** [comment]
This is my attempt at calculating CCN by hand.


![chooseimpl codegen _johannes](https://user-images.githubusercontent.com/12662417/36645943-933ac2be-1a70-11e8-8796-0b42e4737be5.png)
