### ISSUE TITLE
Refactor chooseImpl (Codegen.java)

### ISSUE THREAD

**Issue by bohrnsen** [bohrnsen/json-iterator-java#22]
### Goal
Reduce the cyclomatic complexity from previous 18 down to less than 12.

#### Dependencies
- [x] CCN calculation #2 

##### Graph from previous issue with line numbers
<img width="360" alt="chooseimpl-lines" src="https://user-images.githubusercontent.com/5678082/36642166-a8e95bc8-1a3b-11e8-8af2-21c27eca46bf.png">

**Comment by bohrnsen** [comment]
The idea is to divide the graph into multiple components. I think it would be a good idea to start a new component for each node that is connected to the previous one with a long edge meaning the other condition branch would take a lot of space in the previous component. Each node which has two entrance edges should build an own component, this would not just lower the complexity for each new component but should even result in lower complexity at a whole.

**Comment by bohrnsen** [comment]
The graph may look as following when divided into components as described in the comment above. 
In this graph all "outgoing" edges connected to one node are chosen to be placed to show if the condition is met. The right edge indicates that the statement evaluates as true. 

To get the best possible flow through the graph, the condition statement on line 131 should be inverted (see "!" in front of line number).

<img width="400" alt="chooseimpl-components" src="https://user-images.githubusercontent.com/5678082/36643097-5088bb02-1a47-11e8-9cd6-17cb593a2346.png">

**Comment by bohrnsen** [comment]
The model above would decrease the complexity the most but is not applicable since the project uses the concept of accessing variables changed in another branch. The refactoring mentioned above destroys this ability.

**Comment by Fluffigpegasus** [comment]
Merged into ImproveCoverage. Will close this.
