### ISSUE TITLE
Choose 10 functions with high cyclomatic complexity

### ISSUE THREAD

**Issue by bohrnsen** [bohrnsen/json-iterator-java#24]
Ten functions should be chosen and used in the Ad-Hoc Coverage tool.

From our documentation file these are the functions with the highest complexities:
- readStringSlowPath (IterImpl.java) — 28 CCN --- approx 10 tests
- readStringSlowPath (IterImplForStreaming.java) — 27 CCN --- approx 10 tests
- genObjectUsingStrict (CodegenImplObjectStrict.java) — 26 CCN --- approx 5 tests
- createDecoder (GsonCompatibilityMode.java) — 24 CCN --- approx 14
- genReadOp (CodegenImplNative.java) — 23 CCN --- approx 15
- parse (OmitValue.java) — 21 CCN --- approx 3
- readNumber (IterImplForStreaming.java) — 20 CCN --- approx 1
- updateBindings (Config.java) — 18 CCN --- approx 3
- chooseImpl (Codegen.java) — 18 CCN.  --- approx 7
- skip (IterImplSkip.java) — 18 CCN --- approx 1

**Comment by Fluffigpegasus** [comment]
Sorry, I don't understand what to be done. What is the issue here? Seems like you already have picked 10 functions while creating this issue? It is connected to issue #7 ?

**Comment by bohrnsen** [comment]
I can understand your confusion. I created the issue before I read the sharelatex document and decided to keep it with the data so I can connect it to the next issue.

**Comment by bohrnsen** [comment]
I think we may encounter some issues later with these methods and then we may want to replace one. We can use this issue to link to both the coverage tool and increasing coverage

**Comment by Fluffigpegasus** [comment]
They are now permanent. No change of top 10. Will close this now.
