### ISSUE TITLE
Increase coverage

### ISSUE THREAD

**Issue by bohrnsen** [bohrnsen/json-iterator-java#25]
Leave this issue to document the changes of the coverage obtained throughout the assignment. 

Choose the functions from #7  and check if their coverage is not 100% yet.

#### Dependencies
- [x] Build coverage tool #7 

*Cobertura* only calculates the coverage for an entire class.

### readStringSlowPath (IterImpl.java)  

| Tool                | Before (%)     | After (%)        |
| ------------- | ------------- | ------------- |
| Cobertura     | 72 (120/165) | 75 (124/165)  |
| Ad-Hoc          | 70.00             |  80.00                      |

### readStringSlowPath (IterImplForStreaming.java)

| Tool                | Before (%)     | After (%)        |
| ------------- | ------------- | ------------- |
| Cobertura     | 71 (146/203)  | 75 (154/205)     |
| Ad-Hoc          | 74.42            |    80.00                |

### genObjectUsingStrict (CodegenImplObjectStrict.java) 

| Tool                | Before (%)     | After (%)        |
| ------------- | ------------- | ------------- |
| Cobertura     | 89 (113/126) | 89 (113/126)      |
| Ad-Hoc          | 86.21              |      86.21                  |

### createDecoder (extra/GsonCompatibilityMode.java) 

| Tool                | Before (%)     | After (%)        |
| ------------- | ------------- | ------------- |
| Cobertura     | 89 (57/64)  |     89 (57/64)     |
| Ad-Hoc          | 58.06               |       58.06                 |

### genReadOp (CodegenImplNative.java) 

| Tool                | Before (%)     | After (%)        |
| ------------- | ------------- | ------------- |
| Cobertura     | 54 (27/50)     |   90 (45/50)       |
| Ad-Hoc          | 47.62              |     90.48              |

### parse (spi/OmitValue.java) 

| Tool                | Before (%)     | After (%)        |
| ------------- | ------------- | ------------- |
| Cobertura     | 92 (37/40)     | 100 (40/40)       |
| Ad-Hoc          | 95.00              |    100.00             |

### readNumber (IterImplForStreaming.java)

| Tool                | Before (%)     | After (%)        |
| ------------- | ------------- | ------------- |
| Cobertura     | 71 (146/203)  | 72 (147/203) |
| Ad-Hoc          | 95.83             |  95.83            |

### updateBindings (spi/Config.java) 

| Tool                | Before (%)     | After (%)        |
| ------------- | ------------- | ------------- |
| Cobertura     | 87 (114/130)   | 88 (115/130)  |
| Ad-Hoc          | 91.67              | 98.00            |

### chooseImpl (Codegen.java)

| Tool                | Before (%)     | After (%)        |
| ------------- | ------------- | ------------- |
| Cobertura     | 81 (73/90)          |  81 (73/90)       |
| Ad-Hoc          | 84.62              |   84.62                    |

### skip (IterImplSkip.java)

| Tool                | Before (%)     | After (%)        |
| ------------- | ------------- | ------------- |
| Cobertura     | 56 (13/23)      | 60 (14/23)     |
| Ad-Hoc          | 89.47             |  100.00           |

**Comment by AdderAdder** [comment]
Note that the Cobertura tool gives us the branch coverage for the entire file meanwhile our Ad-Hoc only give us the branch coverage for each function. Thus it was expected that the measured coverage would be different.
