### ISSUE TITLE
Calculate CCN for updateBindings (Config.java) by hand

### ISSUE THREAD

**Issue by Fluffigpegasus** [bohrnsen/json-iterator-java#3]

**Comment by Fluffigpegasus** [comment]
![updatebindings config _madde](https://user-images.githubusercontent.com/14206196/36643078-1fbdf55a-1a47-11e8-8212-2ea4e3715634.png)

**Comment by AdderAdder** [comment]
![updatebindings config java _johannes](https://user-images.githubusercontent.com/12662417/36646053-8d814ca6-1a72-11e8-9158-bea778893e17.png)
