### ISSUE TITLE
Calculate CCN for readNumber (IterImplForStreaming.java) by hand

### ISSUE THREAD

**Issue by AdderAdder** [bohrnsen/json-iterator-java#5]

**Comment by Fluffigpegasus** [comment]
![readnumber iterimplforstreaming _madde](https://user-images.githubusercontent.com/14206196/36642783-a666e7b8-1a44-11e8-9e94-9a4786d774cb.png)

**Comment by AdderAdder** [comment]
![readnumber iterimplforstreaming java _johannes](https://user-images.githubusercontent.com/12662417/36646108-5f519b5a-1a73-11e8-8928-f02ad3c715b5.png)
