### ISSUE TITLE
Calculate CCN for parse (OmitValue.java) by hand

### ISSUE THREAD

**Issue by AdderAdder** [bohrnsen/json-iterator-java#6]

**Comment by Fluffigpegasus** [comment]
![pase omnitvalue _madde](https://user-images.githubusercontent.com/14206196/36642316-2103833e-1a3e-11e8-9cec-90a2866e9a7d.png)

**Comment by AdderAdder** [comment]
![parse omitvalue java _johannes](https://user-images.githubusercontent.com/12662417/36646153-34c0a704-1a74-11e8-9023-cb19d1bb415a.png)
